[[language]]
name = "text"
scope = "text.plain"
file-types = ["txt"]
text-width = 80
rulers = [81]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[[language]]
name = "typst"
scope = "source.typst"
file-types = ["typ"]
text-width = 80
rulers = [81]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
